Repository 100-hours-a-week/10-team-matching-quiz-be, pull requests merged in 2025-05, with the labels that each got.

#36 feat: next round
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/ExceptionMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/InterviewResponseMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/util/InterviewStatus.java
  wingterview/src/main/java/com/easyterview/wingterview/common/util/InterviewUtil.java
  wingterview/src/main/java/com/easyterview/wingterview/common/util/UUIDUtil.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/GlobalExceptionHandler.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/InterviewNotFoundException.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/InvalidUUIDFormatException.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/controller/InterviewController.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/dto/response/NextRoundDto.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewService.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewServiceImpl.java
Labels: BE

#42 feat: interview status api implemented(without question stuff)
  wingterview/build.gradle
  wingterview/src/main/resources/application.yml
Labels: BE

#45 Localdev
  wingterview/src/main/java/com/easyterview/wingterview/chat/entity/ChatEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/chat/entity/ChatroomEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/chat/repository/ChatRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/chat/repository/ChatroomRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/ExceptionMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/InterviewResponseMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/S3ResponseMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/util/TimeUtil.java
  wingterview/src/main/java/com/easyterview/wingterview/config/RestClientConfig.java
  wingterview/src/main/java/com/easyterview/wingterview/config/S3Config.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/GlobalExceptionHandler.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/QuestionOptionNotFoundException.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/controller/InterviewController.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/dto/request/FeedbackRequestDto.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/dto/request/FollowUpQuestionRequest.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/dto/request/QuestionSelectionRequestDto.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/InterviewEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/MainQuestionEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/QuestionHistoryEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/QuestionOptionsEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/ReceivedQuestionEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/repository/MainQuestionRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/repository/QuestionHistoryRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/repository/QuestionOptionsRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/repository/ReceivedQuestionRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewService.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/dto/response/Interviewer.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/service/MatchingServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/s3/controller/S3Controller.java
  wingterview/src/main/java/com/easyterview/wingterview/s3/dto/UploadUrlDto.java
  wingterview/src/main/java/com/easyterview/wingterview/s3/service/S3Service.java
  wingterview/src/main/java/com/easyterview/wingterview/s3/service/S3ServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/user/entity/UserChatroomEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/user/entity/UserEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/user/entity/UserJobInterestEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/user/repository/UserChatroomRepository.java
  wingterview/src/main/resources/application.yml
Labels: 버그-심각, BE

#46 feat: matching algorithm implemented
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/ExceptionMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/common/constants/MatchingResponseMessage.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/GlobalExceptionHandler.java
  wingterview/src/main/java/com/easyterview/wingterview/global/exception/UserNotFoundException.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/controller/InterviewController.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/QuestionOptionsEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/algorithm/MatchingAlgorithm.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/algorithm/MatchingUser.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/controller/MatchingController.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/entity/MatchingParticipantEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/repository/MatchingParticipantRepository.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/service/MatchingService.java
  wingterview/src/main/java/com/easyterview/wingterview/matching/service/MatchingServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/user/entity/UserEntity.java
Labels: BE

#47 fix: questionOptions 404 error fixed
  wingterview/src/main/java/com/easyterview/wingterview/config/CorsConfig.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/dto/request/QuestionCreationRequestDto.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/InterviewEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/entity/QuestionOptionsEntity.java
  wingterview/src/main/java/com/easyterview/wingterview/interview/service/InterviewServiceImpl.java
  wingterview/src/main/java/com/easyterview/wingterview/user/entity/UserEntity.java
Labels: BE

#62 Main
  .github/ISSUE_TEMPLATE/qa-template.md
Labels: 제안
